// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateHost(arg1, arg2, arg3, arg4) {
  return window['go']['main']['LaunchRDPApp']['CreateHost'](arg1, arg2, arg3, arg4);
}

export function CreateHostFull(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['LaunchRDPApp']['CreateHostFull'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function CreateUser(arg1, arg2, arg3, arg4) {
  return window['go']['main']['LaunchRDPApp']['CreateUser'](arg1, arg2, arg3, arg4);
}

export function DeleteHost(arg1) {
  return window['go']['main']['LaunchRDPApp']['DeleteHost'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['LaunchRDPApp']['DeleteUser'](arg1);
}

export function GenerateHostRDP(arg1) {
  return window['go']['main']['LaunchRDPApp']['GenerateHostRDP'](arg1);
}

export function GetHosts() {
  return window['go']['main']['LaunchRDPApp']['GetHosts']();
}

export function GetMonitorWorkAreas() {
  return window['go']['main']['LaunchRDPApp']['GetMonitorWorkAreas']();
}

export function GetMousePosition() {
  return window['go']['main']['LaunchRDPApp']['GetMousePosition']();
}

export function GetUsers() {
  return window['go']['main']['LaunchRDPApp']['GetUsers']();
}

export function GetWindowBorderInfo() {
  return window['go']['main']['LaunchRDPApp']['GetWindowBorderInfo']();
}

export function GetWindowInfo() {
  return window['go']['main']['LaunchRDPApp']['GetWindowInfo']();
}

export function GetWindowState() {
  return window['go']['main']['LaunchRDPApp']['GetWindowState']();
}

export function GetWorkArea() {
  return window['go']['main']['LaunchRDPApp']['GetWorkArea']();
}

export function LaunchRDP(arg1, arg2, arg3, arg4) {
  return window['go']['main']['LaunchRDPApp']['LaunchRDP'](arg1, arg2, arg3, arg4);
}

export function LogMessage(arg1, arg2) {
  return window['go']['main']['LaunchRDPApp']['LogMessage'](arg1, arg2);
}

export function PersistWindowState() {
  return window['go']['main']['LaunchRDPApp']['PersistWindowState']();
}

export function UpdateHost(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['LaunchRDPApp']['UpdateHost'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateHostFull(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['LaunchRDPApp']['UpdateHostFull'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function UpdateUser(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['LaunchRDPApp']['UpdateUser'](arg1, arg2, arg3, arg4, arg5);
}
