// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function CreateHost(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function CreateHostFull(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:number,arg7:number,arg8:number,arg9:number,arg10:boolean,arg11:boolean):Promise<void>;

export function CreateUser(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteHost(arg1:string):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function GenerateHostRDP(arg1:string):Promise<string>;

export function GetHosts():Promise<Array<models.Host>>;

export function GetMonitorWorkAreas():Promise<Array<main.MonitorWorkArea>>;

export function GetMousePosition():Promise<main.MousePosition>;

export function GetUsers():Promise<Array<models.User>>;

export function GetWindowBorderInfo():Promise<main.WindowBorderInfo>;

export function GetWindowInfo():Promise<main.WindowBorderInfo>;

export function GetWindowState():Promise<main.WindowState>;

export function GetWorkArea():Promise<main.WorkArea>;

export function LaunchRDP(arg1:string,arg2:string,arg3:number,arg4:number):Promise<boolean>;

export function LogMessage(arg1:string,arg2:string):Promise<void>;

export function PersistWindowState():Promise<void>;

export function UpdateHost(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;

export function UpdateHostFull(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string,arg7:number,arg8:number,arg9:number,arg10:number,arg11:boolean,arg12:boolean):Promise<void>;

export function UpdateUser(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;
